# Generated by Django 3.2.9 on 2021-11-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occassion', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Booking')),
                ('attendees', models.IntegerField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('R', 'Brunch'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('hourly', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('booked_dates', models.DateField(verbose_name='Booked Dates')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
