# Generated by Django 3.2.9 on 2021-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendees',
            field=models.IntegerField(default=2),
        ),
    ]
