# Generated by Django 3.2.9 on 2021-11-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chef',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.chef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
            preserve_default=False,
        ),
    ]
