# Generated by Django 3.2.9 on 2021-11-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211127_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chef')),
            ],
        ),
    ]
