# Generated by Django 3.2.9 on 2021-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
