# Generated by Django 3.2.9 on 2021-12-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_booking_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
